@startuml

package controller {
  package partita {
    package fasiGioco {
      class FineGioco
      class FineVolo
      class Inizializzazione
      package composizioneNave {
        class ComposizioneNave
        class ManagerTurnoComposizione
      }
      package volo {
        class ManagerDiVolo
        class Volo
      }
    }
    class LivelliPartita
    class ModalitaGioco
    class Partita
  }
  package servizi {
    class ServizioAssemblaggio
    class ServizioCarte
    class ServizioDadi
    class ServizioTitoli
  }
}

@enduml